### ISSUE TITLE
ブログ記事を削除できない

### ISSUE THREAD

**Issue by mcfyoshitake** [seungyeong/test_2#1]
# 事象
ブログ記事を削除しようとしてもShow画面に飛ぶ
[![Image from Gyazo](https://i.gyazo.com/f84ed975731326cef0dab6da0ee2d2e4.png)](https://gyazo.com/f84ed975731326cef0dab6da0ee2d2e4)

# 対策
おそらく以下のリンク先の対策をとればよいと思われる。
https://qiita.com/sijiaoh/items/973f9f7d91d669a79ef5

**Comment by seungyeong** [comment]
直しました。コードに問題がなくて、WebpackerとBabelに問題があって スクリプトがちゃんと動作されませんでした。
